---
title: "plot_data"
author: "Zhirou Zhou"
date: "12/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
setwd('~/Documents/Rochester/BST430_Intro_Statistical_Computing/Final_Project/Option1/final_project1_files')
library("plot3D")
library("colorspace")
```

```{r}
# load the data frame containing all data
load("~/Documents/Rochester/BST430_Intro_Statistical_Computing/Final_Project/Option1/df.merge.rdata")
```

```{r}
# plot.pc: plot 3D scatterplot of traits and connectome PC scores
# Inputs:
# - df: dataframe containing traits and PC scores. Default as `df.merge`
# - ntraits: the order of the trait to be plotted
# - theta, phi: the angles defining the viewing direction. theta gives the azimuthal direction and phi the colatitude
# - colorpal: Color palette to be used for coloring the colvar variable
# Outputs: dataframe `df.plot`, containing the first 3 PC scores and the specific trait score of first and last 100 subjects

plot.pc = function(df = df.merge, ntraits, theta, phi, colorpal) {
  ntraits = ntraits + 481 # locate the trait in `df.merge`
  df.reorder = df[order(df[,ntraits]),] # sort all subjects according to nth trait
  df.part = df.reorder[, c(122:124, ntraits)] # subset the df with 3 PC scores and trait
  df.remove.na = df.part[complete.cases(df.part),] # remove the uncomplete cases
  df.plot = rbind(head(df.remove.na, 100), tail(df.remove.na, 100)) # take out the first and last 100 subjects
  colnames(df.plot) = c("U1", "U2", "U3", "trait_score")
  plot.pc = scatter3D(df.plot$U1, df.plot$U2, df.plot$U3, colvar = df.plot$trait_score, 
                      theta = theta, phi = phi, col = colorpal, pch = 19, bty = "g", 
                      clab = c("Higher","Trait Score"), 
                      colkey = list(length = 0.5, width = 0.5, cex.clab = 0.75), 
                      xlab = "U1", ylab = "U2", zlab = "U3", cex = 0.6, 
                      ticktype = "detailed")
  return(df.plot = df.plot)
}

# plot.pc.al: plot 3D scatterplot of alcohol related traits and connectome PC scores

plot.pc.al = function(df = df.merge, ntraits, theta, phi, colorpal) {
  ntraits = ntraits + 481 # locate the trait in `df.merge`
  df.reorder = df[order(df[,ntraits]),] # sort all subjects according to nth trait
  df.part = df.reorder[, c(122:124, ntraits)] # subset the df with 3 PC scores and trait
  df.remove.na = df.part[complete.cases(df.part),] # remove the uncomplete cases
  df.plot = rbind(df.remove.na[df.remove.na[,4] == 1,], 
                  df.remove.na[df.remove.na[,4] == 6,]) # take out the subjects with low value and high value
  colnames(df.plot) = c("U1", "U2", "U3", "trait_score")
  plot.pc = scatter3D(df.plot$U1, df.plot$U2, df.plot$U3, colvar = df.plot$trait_score, 
                      theta = theta, phi = phi, col = colorpal, pch = 19, bty = "g", 
                      clab = c("Higher","Trait Score"), 
                      colkey = list(length = 0.5, width = 0.5, cex.clab = 0.75), 
                      xlab = "U1", ylab = "U2", zlab = "U3", cex = 0.6, 
                      ticktype = "detailed")
  return(df.plot = df.plot)
}
```
