---
title: "hypothesis_test_zhou"
author: "Zhirou Zhou"
date: "12/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
setwd('~/Documents/Rochester/BST430_Intro_Statistical_Computing/Final_Project/Option1/final_project1_files')
library("MVN")
library("mvnormtest")
```

```{r}
# load the data frame containing all data
load("~/Documents/Rochester/BST430_Intro_Statistical_Computing/Final_Project/Option1/df.merge.rdata")
```

```{r}
# test.pc.data: prepare the data needed for hypothesis test
# Inputs:
# - df: dataframe containing traits and PC scores. Default is `df.merge`
# - ntraits: the order of the trait to be plotted
# Outputs: dataframe `df.test`, containing the first 3 PC scores, the specific trait score and the group of first and last 100 subjects

test.pc.data = function(df = df.merge, ntraits) {
  ntraits = ntraits + 481
  df.reorder = df[order(df[,ntraits]),] # sort all subjects according to nth trait
  df.part = df.reorder[, c(122:124, ntraits)] # subset the df with 3 PC scores and trait
  df.remove.na = df.part[complete.cases(df.part),] # remove the uncomplete cases
  df.test = rbind(head(df.remove.na, 100), tail(df.remove.na, 100)) # take out the first and last 100 subjects
  df.test$group[1:100] = 0
  df.test$group[101:200] = 1
  colnames(df.test) = c("U1", "U2", "U3", "trait_score", "group")
  return(df.test = df.test)
}

# test.pc.data.al: prepare the data needed for hypothesis test (alcohol related traits)

test.pc.data.al = function(df = df.merge, ntraits) {
  ntraits = ntraits + 481
  df.reorder = df[order(df[,ntraits]),] # sort all subjects according to nth trait
  df.part = df.reorder[, c(122:124, ntraits)] # subset the df with 3 PC scores and trait
  df.remove.na = df.part[complete.cases(df.part),] # remove the uncomplete cases
  df.test = rbind(df.remove.na[df.remove.na[,4] == 1,], 
                  df.remove.na[df.remove.na[,4] == 6,]) # take out the subjects with low value and high value
  df.test$group[1:341] = 0
  df.test$group[52:341] = 1
  colnames(df.test) = c("U1", "U2", "U3", "trait_score", "group")
  return(df.test = df.test)
}
```

```{r}
# perform hypothesis test for trait: 'Motor: Endurance age adjusted'
df.test = test.pc.data(ntraits = 49)

# perform multivariate normality test over first 3 PC scores
nor.test = mvn(data = df.test[,1:3], mvnTest = "hz", 
               multivariateOutlierMethod = "adj", showNewData = TRUE)
nor.test$multivariateNormality
df.test.new = merge(nor.test$newData, df.test, by.x = c("U1", "U2", "U3"), by.y = c("U1", "U2", "U3")) # derive the new data set without outliers

nor.test.1 = mvn(data = df.test.new[,1:3], mvnTest = "hz", 
               multivariateOutlierMethod = "adj", showNewData = TRUE) # redo the multivariate normality test over the new data set without outliers
nor.test.1$multivariateNormality

# perform homogeneity of variance and covariance test over first 3 PC scores
bartlett.test(U1 + U2 + U3 ~ group, data = df.test.new)
bartlett.test(interaction(U1, U2) ~ group, data = df.test.new)
bartlett.test(interaction(U2, U3) ~ group, data = df.test.new)
bartlett.test(interaction(U1, U3) ~ group, data = df.test.new)

# compute MANOVA test
pc.man = manova(cbind(U1, U2, U3) ~ group, data = df.test.new)
summary(pc.man)
#summary.aov(pc.man)
```

```{r}
# perform hypothesis test for trait: 'Motor: Strength age adjusted'
df.test = test.pc.data(ntraits = 52)

# perform multivariate normality test over first 3 PC scores
nor.test = mvn(data = df.test[,1:3], mvnTest = "hz", multivariateOutlierMethod = "adj")
nor.test$multivariateNormality

# perform homogeneity of variance and covariance test over first 3 PC scores
bartlett.test(U1 + U2 + U3 ~ group, data = df.test)
bartlett.test(interaction(U1, U2) ~ group, data = df.test)
bartlett.test(interaction(U2, U3) ~ group, data = df.test.new)
bartlett.test(interaction(U1, U3) ~ group, data = df.test.new)

# compute MANOVA test
pc.man = manova(cbind(U1, U2, U3) ~ group, data = df.test)
summary(pc.man)
#summary.aov(pc.man)
```

```{r}
# perform hypothesis test for trait: 'Substance use: alcohol'
df.test = test.pc.data.al(ntraits = 58)

# perform multivariate normality test over first 3 PC scores
nor.test = mvn(data = df.test[,1:3], mvnTest = "hz", 
               multivariateOutlierMethod = "adj", showNewData = TRUE)
nor.test$multivariateNormality
df.test.new = merge(nor.test$newData, df.test, by.x = c("U1", "U2", "U3"), by.y = c("U1", "U2", "U3")) # derive the new data set without outliers

nor.test.1 = mvn(data = df.test.new[,1:3], mvnTest = "hz", 
               multivariateOutlierMethod = "adj", showNewData = TRUE) # redo the multivariate normality test over the new data set without outliers
nor.test.1$multivariateNormality

# perform homogeneity of variance and covariance test over first 3 PC scores
bartlett.test(U1 + U2 + U3 ~ group, data = df.test.new)
bartlett.test(interaction(U1, U2) ~ group, data = df.test.new)
bartlett.test(interaction(U2, U3) ~ group, data = df.test.new)
bartlett.test(interaction(U1, U3) ~ group, data = df.test.new)

# compute MANOVA test
pc.man = manova(cbind(U1, U2, U3) ~ group, data = df.test.new)
summary(pc.man)
#summary.aov(pc.man)
```

```{r}
# perform hypothesis test for trait: 'Sensory: Audition'
df.test = test.pc.data(ntraits = 132)

# perform multivariate normality test over first 3 PC scores
nor.test = mvn(data = df.test[,1:3], mvnTest = "hz", multivariateOutlierMethod = "adj")
nor.test$multivariateNormality

# perform homogeneity of variance and covariance test over first 3 PC scores
bartlett.test(U1 + U2 + U3 ~ group, data = df.test)
bartlett.test(interaction(U1, U2) ~ group, data = df.test)
bartlett.test(interaction(U2, U3) ~ group, data = df.test.new)
bartlett.test(interaction(U1, U3) ~ group, data = df.test.new)

# compute MANOVA test
pc.man = manova(cbind(U1, U2, U3) ~ group, data = df.test)
summary(pc.man)
#summary.aov(pc.man)
```